// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoa43GhYBDwVYxhNy9ATh7AaFZV8IGGhY',
    appId: '1:1045716649982:web:f2818b5037e334c44222af',
    messagingSenderId: '1045716649982',
    projectId: 'rumanka-a1a2a3',
    authDomain: 'rumanka-a1a2a3.firebaseapp.com',
    storageBucket: 'rumanka-a1a2a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-NbG7pPHNl0MpW6N0vLa9Kh2RY7utKA',
    appId: '1:1045716649982:android:9c93d316a4a3fe344222af',
    messagingSenderId: '1045716649982',
    projectId: 'rumanka-a1a2a3',
    storageBucket: 'rumanka-a1a2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaP_sZtvBJkWIZCKN7cLN-BunTTvikqks',
    appId: '1:1045716649982:ios:807c3fb39efaad7b4222af',
    messagingSenderId: '1045716649982',
    projectId: 'rumanka-a1a2a3',
    storageBucket: 'rumanka-a1a2a3.firebasestorage.app',
    iosBundleId: 'com.example.appRumanka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaP_sZtvBJkWIZCKN7cLN-BunTTvikqks',
    appId: '1:1045716649982:ios:807c3fb39efaad7b4222af',
    messagingSenderId: '1045716649982',
    projectId: 'rumanka-a1a2a3',
    storageBucket: 'rumanka-a1a2a3.firebasestorage.app',
    iosBundleId: 'com.example.appRumanka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoa43GhYBDwVYxhNy9ATh7AaFZV8IGGhY',
    appId: '1:1045716649982:web:6e2a5bcf5985656a4222af',
    messagingSenderId: '1045716649982',
    projectId: 'rumanka-a1a2a3',
    authDomain: 'rumanka-a1a2a3.firebaseapp.com',
    storageBucket: 'rumanka-a1a2a3.firebasestorage.app',
  );
}
